#pragma include "../include/module.glsl"

DEFINE_INPUTS_RGBA()
DEFINE_INPUTS_RGBA_WITH(2)
DEFINE_INPUTS_RGBA_WITH(3)
DEFINE_INPUTS_RGBA_WITH(4)
DEFINE_INPUTS_RGBA_WITH(5)
DEFINE_INPUTS_RGBA_WITH(6)
DEFINE_INPUTS_RGBA_WITH(7)

DEFINE_OUTPUTS_RGBA_1234()

void main() {

}
